import { DeliveryFormValues } from '@/lib/validations';
import { DriverFormValues } from '@/lib/validations/driver-schema';

export const driversData: DriverFormValues[] = [
  {
    name: 'Pepa Novák',
    car: 'Ford Transit (2BA 1234)',
  },
  {
    name: 'Karel Vomáčka',
    car: 'Volkswagen Crafter (3CD 5678)',
  },
  {
    name: 'Jana Rychlá',
    car: 'Mercedes-Benz Sprinter (4EF 9012)',
  },
];

export const deliveriesData: DeliveryFormValues[] = [
  {
    recipientName: 'Jan Novák',
    address: 'Wolkerova 12, Prostějov',
    orderNumber: 'ORD-1001',
    status: 'PENDING',
  },
  {
    recipientName: 'Petra Dvořáková',
    address: 'Smetanova 5, Plumlov',
    orderNumber: 'ORD-1002',
    status: 'PENDING',
  },
  {
    recipientName: 'Tomáš Beneš',
    address: 'Náměstí T. G. Masaryka 8, Kostelec na Hané',
    orderNumber: 'ORD-1003',
    status: 'PENDING',
  },
  {
    recipientName: 'Lucie Králová',
    address: 'Olomoucká 42, Držovice',
    orderNumber: 'ORD-1004',
    status: 'FAILED',
  },
  {
    recipientName: 'Michal Horák',
    address: 'Nerudova 17, Čechy pod Kosířem',
    orderNumber: 'ORD-1005',
    status: 'PENDING',
  },
  {
    recipientName: 'Anna Štěpánová',
    address: 'Za Humny 21, Mostkovice',
    orderNumber: 'ORD-1006',
    status: 'PENDING',
  },
  {
    recipientName: 'David Jelínek',
    address: 'Komenského 3, Smržice',
    orderNumber: 'ORD-1007',
    status: 'DELIVERED',
  },
  {
    recipientName: 'Barbora Kovářová',
    address: 'Dukelská 9, Kralice na Hané',
    orderNumber: 'ORD-1008',
    status: 'PENDING',
  },
  {
    recipientName: 'Roman Svoboda',
    address: 'Hlavní 112, Vrbátky',
    orderNumber: 'ORD-1009',
    status: 'PENDING',
  },
  {
    recipientName: 'Jitka Malá',
    address: 'Lutínská 6, Třebčín (Lutín)',
    orderNumber: 'ORD-1010',
    status: 'PENDING',
  },
  {
    recipientName: 'Ondřej Kučera',
    address: 'Dolní 14, Ptení',
    orderNumber: 'ORD-1011',
    status: 'PENDING',
  },
  {
    recipientName: 'Simona Fialová',
    address: 'U Rybníka 3, Konice',
    orderNumber: 'ORD-1012',
    status: 'PENDING',
  },
  {
    recipientName: 'Jaroslav Marek',
    address: 'Na Zábraní 22, Bedihošť',
    orderNumber: 'ORD-1013',
    status: 'DELIVERED',
  },
  {
    recipientName: 'Klára Pokorná',
    address: 'Nádražní 7, Dobromilice',
    orderNumber: 'ORD-1014',
    status: 'PENDING',
  },
  {
    recipientName: 'Kamil Hrubý',
    address: 'Kostelní 2, Výšovice',
    orderNumber: 'ORD-1015',
    status: 'PENDING',
  },
  {
    recipientName: 'Martin Šeda',
    address: 'Lipová 18, Čelechovice na Hané',
    orderNumber: 'ORD-1016',
    status: 'PENDING',
  },
  {
    recipientName: 'Eliška Veselá',
    address: 'Tyršova 4, Lutín',
    orderNumber: 'ORD-1017',
    status: 'PENDING',
  },
  {
    recipientName: 'Václav Konečný',
    address: 'Nová 7, Laškov',
    orderNumber: 'ORD-1018',
    status: 'IN_TRANSIT',
  },
  {
    recipientName: 'Monika Hradilová',
    address: 'Háj 3, Určice',
    orderNumber: 'ORD-1019',
    status: 'PENDING',
  },
  {
    recipientName: 'Daniel Krejčí',
    address: 'Sportovní 11, Bousín',
    orderNumber: 'ORD-1020',
    status: 'PENDING',
  },
  {
    recipientName: 'Alena Krupová',
    address: 'Pod Kostelem 9, Olšany u Prostějova',
    orderNumber: 'ORD-1021',
    status: 'PENDING',
  },
  {
    recipientName: 'Pavel Šustek',
    address: 'Zahradní 34, Lutín',
    orderNumber: 'ORD-1022',
    status: 'PENDING',
  },
  {
    recipientName: 'Ivana Marková',
    address: 'Tovární 12, Prostějov',
    orderNumber: 'ORD-1023',
    status: 'PENDING',
  },
  {
    recipientName: 'Filip Krčmář',
    address: 'Svatoplukova 21, Prostějov',
    orderNumber: 'ORD-1024',
    status: 'PENDING',
  },
  {
    recipientName: 'Radka Zlámalová',
    address: 'Mlýnská 5, Plumlov',
    orderNumber: 'ORD-1025',
    status: 'PENDING',
  },
  {
    recipientName: 'Adam Soukup',
    address: 'Husova 3, Kostelec na Hané',
    orderNumber: 'ORD-1026',
    status: 'PENDING',
  },
  {
    recipientName: 'Kamila Trojková',
    address: 'Skálovo náměstí 7, Konice',
    orderNumber: 'ORD-1027',
    status: 'PENDING',
  },
  {
    recipientName: 'Tomáš Konečný',
    address: 'Nádražní 18, Němčice nad Hanou',
    orderNumber: 'ORD-1028',
    status: 'PENDING',
  },
  {
    recipientName: 'Ema Kubešová',
    address: 'Hlavní 45, Výšovice',
    orderNumber: 'ORD-1029',
    status: 'PENDING',
  },
  {
    recipientName: 'Jaroslav Benda',
    address: 'U Rybníka 12, Mostkovice',
    orderNumber: 'ORD-1030',
    status: 'PENDING',
  },

  {
    recipientName: 'Karolína Horská',
    address: 'Školní 4, Smržice',
    orderNumber: 'ORD-1031',
    status: 'PENDING',
  },
  {
    recipientName: 'Marek Bláha',
    address: 'Ořechová 6, Určice',
    orderNumber: 'ORD-1032',
    status: 'PENDING',
  },
  {
    recipientName: 'Tereza Halová',
    address: 'Na Trávníku 10, Bedihošť',
    orderNumber: 'ORD-1033',
    status: 'PENDING',
  },
  {
    recipientName: 'Roman Černý',
    address: 'Hlavní 77, Vrbátky',
    orderNumber: 'ORD-1034',
    status: 'PENDING',
  },
  {
    recipientName: 'Nikola Slámová',
    address: 'Školní 3, Ptení',
    orderNumber: 'ORD-1035',
    status: 'PENDING',
  },
  {
    recipientName: 'Ondřej Tomek',
    address: 'Lipová 2, Čelechovice na Hané',
    orderNumber: 'ORD-1036',
    status: 'PENDING',
  },
  {
    recipientName: 'Magdaléna Bednářová',
    address: 'Lidická 8, Laškov',
    orderNumber: 'ORD-1037',
    status: 'PENDING',
  },
  {
    recipientName: 'Robert Jeřábek',
    address: 'Olomoucká 15, Držovice',
    orderNumber: 'ORD-1038',
    status: 'PENDING',
  },
  {
    recipientName: 'Simona Vávrová',
    address: 'Lhotky 22, Prostějovičky',
    orderNumber: 'ORD-1039',
    status: 'PENDING',
  },
  {
    recipientName: 'David Polák',
    address: 'Nerudova 11, Prostějov',
    orderNumber: 'ORD-1040',
    status: 'PENDING',
  },

  {
    recipientName: 'Helena Lorencová',
    address: 'Pod Hřištěm 3, Kralice na Hané',
    orderNumber: 'ORD-1041',
    status: 'PENDING',
  },
  {
    recipientName: 'Milan Gregor',
    address: 'Zborovská 25, Prostějov',
    orderNumber: 'ORD-1042',
    status: 'PENDING',
  },
  {
    recipientName: 'Andrea Smejkalová',
    address: 'Luční 14, Mostkovice',
    orderNumber: 'ORD-1043',
    status: 'PENDING',
  },
  {
    recipientName: 'Petr Kříž',
    address: 'Květná 6, Plumlov',
    orderNumber: 'ORD-1044',
    status: 'PENDING',
  },
  {
    recipientName: 'Monika Valová',
    address: 'Sokolská 9, Smržice',
    orderNumber: 'ORD-1045',
    status: 'PENDING',
  },
  {
    recipientName: 'Radim Pařil',
    address: 'Nádražní 2, Určice',
    orderNumber: 'ORD-1046',
    status: 'PENDING',
  },
  {
    recipientName: 'Alice Králová',
    address: 'Vodní 10, Tovačov',
    orderNumber: 'ORD-1047',
    status: 'PENDING',
  },
  {
    recipientName: 'Jana Koutná',
    address: 'Hanácká 4, Dub nad Moravou',
    orderNumber: 'ORD-1048',
    status: 'PENDING',
  },
  {
    recipientName: 'Vojtěch Dobeš',
    address: 'Lhota 18, Přemyslovice',
    orderNumber: 'ORD-1049',
    status: 'PENDING',
  },
  {
    recipientName: 'Radka Michálková',
    address: 'Háj 55, Stařechovice',
    orderNumber: 'ORD-1050',
    status: 'PENDING',
  },

  {
    recipientName: 'Michal Brzobohatý',
    address: 'U Kapličky 7, Bílovice-Lutotín',
    orderNumber: 'ORD-1051',
    status: 'PENDING',
  },
  {
    recipientName: 'Zuzana Havlíková',
    address: 'Mlýnská 3, Kostelec na Hané',
    orderNumber: 'ORD-1052',
    status: 'PENDING',
  },
  {
    recipientName: 'Martin Prášek',
    address: 'Trávníky 4, Konice',
    orderNumber: 'ORD-1053',
    status: 'PENDING',
  },
  {
    recipientName: 'Nela Urbánková',
    address: 'Husovo náměstí 19, Němčice nad Hanou',
    orderNumber: 'ORD-1054',
    status: 'PENDING',
  },
  {
    recipientName: 'Pavel Karas',
    address: 'Nad Zahradami 6, Dobromilice',
    orderNumber: 'ORD-1055',
    status: 'PENDING',
  },
  {
    recipientName: 'Romana Balcarová',
    address: 'U Sila 8, Laškov',
    orderNumber: 'ORD-1056',
    status: 'PENDING',
  },
  {
    recipientName: 'Karel Jon',
    address: 'Hlavní 29, Bohuslavice',
    orderNumber: 'ORD-1057',
    status: 'PENDING',
  },
  {
    recipientName: 'Irena Mašková',
    address: 'Opletalova 15, Prostějov',
    orderNumber: 'ORD-1058',
    status: 'PENDING',
  },
  {
    recipientName: 'Vít Stříteský',
    address: 'U Hřiště 11, Čelechovice na Hané',
    orderNumber: 'ORD-1059',
    status: 'PENDING',
  },
  {
    recipientName: 'Kristýna Holá',
    address: 'Nerudova 3, Smržice',
    orderNumber: 'ORD-1060',
    status: 'PENDING',
  },

  {
    recipientName: 'Sabina Doležalová',
    address: 'Školní 10, Ptení',
    orderNumber: 'ORD-1061',
    status: 'PENDING',
  },
  {
    recipientName: 'Radim Kroupa',
    address: 'Kostelecká 18, Prostějov',
    orderNumber: 'ORD-1062',
    status: 'PENDING',
  },
  {
    recipientName: 'Johana Vítková',
    address: 'U Kapličky 5, Mostkovice',
    orderNumber: 'ORD-1063',
    status: 'PENDING',
  },
  {
    recipientName: 'Štěpán Mach',
    address: 'Na Kopci 12, Plumlov',
    orderNumber: 'ORD-1064',
    status: 'PENDING',
  },
  {
    recipientName: 'Eva Holubová',
    address: 'Smetanova 2, Určice',
    orderNumber: 'ORD-1065',
    status: 'PENDING',
  },
  {
    recipientName: 'Petr Bezděk',
    address: 'Nádražní 4, Čechy pod Kosířem',
    orderNumber: 'ORD-1066',
    status: 'PENDING',
  },
  {
    recipientName: 'Linda Kabelová',
    address: 'Hlavní 19, Lutín',
    orderNumber: 'ORD-1067',
    status: 'PENDING',
  },
  {
    recipientName: 'Lukáš Veselý',
    address: 'U Rybníka 1, Třebčín',
    orderNumber: 'ORD-1068',
    status: 'PENDING',
  },
  {
    recipientName: 'Andrea Fojtíková',
    address: 'Školní 6, Stařechovice',
    orderNumber: 'ORD-1069',
    status: 'PENDING',
  },
  {
    recipientName: 'Roman Hudeček',
    address: 'Nová 14, Lešany',
    orderNumber: 'ORD-1070',
    status: 'PENDING',
  },

  {
    recipientName: 'Nikol Švarcová',
    address: 'Hlavní 3, Krasice (Prostějov)',
    orderNumber: 'ORD-1071',
    status: 'PENDING',
  },
  {
    recipientName: 'Kamil Zbořil',
    address: 'Pod Lipami 18, Vrahovice (Prostějov)',
    orderNumber: 'ORD-1072',
    status: 'PENDING',
  },
  {
    recipientName: 'Barbora Šafářová',
    address: 'Blahoslavova 7, Prostějov',
    orderNumber: 'ORD-1073',
    status: 'PENDING',
  },
  {
    recipientName: 'Dominik Hrabal',
    address: 'Mlékařská 4, Prostějov',
    orderNumber: 'ORD-1074',
    status: 'PENDING',
  },
  {
    recipientName: 'Eva Jandová',
    address: 'Držovská 12, Čechovice (Prostějov)',
    orderNumber: 'ORD-1075',
    status: 'PENDING',
  },
  {
    recipientName: 'Richard Pokorný',
    address: 'Trávnická 35, Prostějov',
    orderNumber: 'ORD-1076',
    status: 'PENDING',
  },
  {
    recipientName: 'Sabina Kolaříková',
    address: 'Dr. Horáka 21, Prostějov',
    orderNumber: 'ORD-1077',
    status: 'PENDING',
  },
  {
    recipientName: 'Michal Dolejš',
    address: 'Wolkerova 36, Prostějov',
    orderNumber: 'ORD-1078',
    status: 'PENDING',
  },
  {
    recipientName: 'Lucie Švihálková',
    address: 'Majakovského 4, Prostějov',
    orderNumber: 'ORD-1079',
    status: 'PENDING',
  },
  {
    recipientName: 'Patrik Sedláček',
    address: 'Svatoplukova 11, Prostějov',
    orderNumber: 'ORD-1080',
    status: 'PENDING',
  },

  {
    recipientName: 'Natálie Vocetková',
    address: 'Vodní 9, Němčice nad Hanou',
    orderNumber: 'ORD-1081',
    status: 'PENDING',
  },
  {
    recipientName: 'Šimon Klus',
    address: 'Nádražní 7, Tovačov',
    orderNumber: 'ORD-1082',
    status: 'PENDING',
  },
  {
    recipientName: 'Elena Zlámalová',
    address: 'Mánesova 2, Plumlov',
    orderNumber: 'ORD-1083',
    status: 'PENDING',
  },
  {
    recipientName: 'Kryštof Pivoňka',
    address: 'U Svatého Jána 4, Přemyslovice',
    orderNumber: 'ORD-1084',
    status: 'PENDING',
  },
  {
    recipientName: 'Monika Drmolová',
    address: 'Družstevní 16, Čelechovice na Hané',
    orderNumber: 'ORD-1085',
    status: 'PENDING',
  },
  {
    recipientName: 'Radek Bartl',
    address: 'U Hřiště 9, Kralice na Hané',
    orderNumber: 'ORD-1086',
    status: 'PENDING',
  },
  {
    recipientName: 'Daniela Veselá',
    address: 'Za Školou 5, Smržice',
    orderNumber: 'ORD-1087',
    status: 'PENDING',
  },
  {
    recipientName: 'Patrik Kovář',
    address: 'Luční 11, Výšovice',
    orderNumber: 'ORD-1088',
    status: 'PENDING',
  },
  {
    recipientName: 'Elen Tichá',
    address: 'Hlavní 17, Ptení',
    orderNumber: 'ORD-1089',
    status: 'PENDING',
  },
  {
    recipientName: 'Radim Jindra',
    address: 'U Sokolovny 3, Držovice',
    orderNumber: 'ORD-1090',
    status: 'PENDING',
  },

  {
    recipientName: 'Nikola Fuseková',
    address: 'Sadová 8, Nezamyslice',
    orderNumber: 'ORD-1091',
    status: 'PENDING',
  },
  {
    recipientName: 'Tomáš Řehák',
    address: 'Hlavní 22, Dobromilice',
    orderNumber: 'ORD-1092',
    status: 'PENDING',
  },
  {
    recipientName: 'Radka Konečná',
    address: 'Zahradní 3, Stařechovice',
    orderNumber: 'ORD-1093',
    status: 'PENDING',
  },
  {
    recipientName: 'Filip Tvrdík',
    address: 'Za Kostelem 5, Přemyslovice',
    orderNumber: 'ORD-1094',
    status: 'PENDING',
  },
  {
    recipientName: 'Eliška Doubravová',
    address: 'Olomoucká 31, Lutín',
    orderNumber: 'ORD-1095',
    status: 'PENDING',
  },
  {
    recipientName: 'Jan Machala',
    address: 'Mlýnská 7, Bedihošť',
    orderNumber: 'ORD-1096',
    status: 'PENDING',
  },
  {
    recipientName: 'Ludmila Švecová',
    address: 'Zámecká 4, Konice',
    orderNumber: 'ORD-1097',
    status: 'PENDING',
  },
  {
    recipientName: 'Daniel Adam',
    address: 'Hlavní 6, Lešany',
    orderNumber: 'ORD-1098',
    status: 'PENDING',
  },
  {
    recipientName: 'Barbora Rozsívalová',
    address: 'Krátká 2, Plumlov',
    orderNumber: 'ORD-1099',
    status: 'PENDING',
  },
  {
    recipientName: 'Roman Vlk',
    address: 'Kollárova 12, Prostějov',
    orderNumber: 'ORD-1100',
    status: 'PENDING',
  },

  {
    recipientName: 'Milan Kameník',
    address: 'Vodní 5, Tovačov',
    orderNumber: 'ORD-1101',
    status: 'PENDING',
  },
  {
    recipientName: 'Lenka Kašpárková',
    address: 'Husova 9, Němčice nad Hanou',
    orderNumber: 'ORD-1102',
    status: 'PENDING',
  },
  {
    recipientName: 'Josef Baláš',
    address: 'U Hájenky 12, Plumlov',
    orderNumber: 'ORD-1103',
    status: 'PENDING',
  },
  {
    recipientName: 'Petr Jurník',
    address: 'Hlavní 20, Mostkovice',
    orderNumber: 'ORD-1104',
    status: 'PENDING',
  },
  {
    recipientName: 'Kamila Šteflová',
    address: 'Kostelecká 9, Prostějov',
    orderNumber: 'ORD-1105',
    status: 'PENDING',
  },
  {
    recipientName: 'Žaneta Bílková',
    address: 'U Formanky 3, Vrbátky',
    orderNumber: 'ORD-1106',
    status: 'PENDING',
  },
  {
    recipientName: 'Ondřej Smolík',
    address: 'U Rybníka 7, Určice',
    orderNumber: 'ORD-1107',
    status: 'PENDING',
  },
  {
    recipientName: 'Kristýnа Večeřová',
    address: 'Školní 2, Laškov',
    orderNumber: 'ORD-1108',
    status: 'PENDING',
  },
  {
    recipientName: 'Richard Holík',
    address: 'Za Humny 16, Čelechovice na Hané',
    orderNumber: 'ORD-1109',
    status: 'PENDING',
  },
  {
    recipientName: 'Radka Hanzelová',
    address: 'Lutínská 15, Třebčín',
    orderNumber: 'ORD-1110',
    status: 'PENDING',
  },
];
